#workspace:
#  base: /lama
#  path: src/github.com/michigg/lama

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags
 
- name: build
  privileged: true
  image: docker/compose:1.24.1
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.test.yml build --no-cache

- name: test
  image: docker/compose:1.24.1
  privileged: true
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - echo "-------- docker-compose down --------"
  - docker-compose -f docker-compose.test.yml down
  - echo "-------- docker-compose up -d --------"
  - docker-compose -f docker-compose.test.yml up -d
  - echo "-------- docker-compose ps --------"
  - docker-compose -f docker-compose.test.yml ps
  - echo "-------- docker-compose test --------"
  - docker-compose -f docker-compose.test.yml run ci_lama /lama/entrypoint.sh

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: michigg/lama
    tags: latest
    
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_chat_id
  message: >
   {{#success build.status}}
     build {{build.number}} succeeded. Good job.
   {{else}}
     build {{build.number}} failed. Fix me please.
   {{/success}}

trigger:
  branch:
  - master
  event:
  - push

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
