kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags
 
- name: build
  image: docker/compose:1.24.1
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - build

- name: test
  image: docker/compose:1.24.1
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - exec lama python3 manage.py test

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: michigg/lama
    tags: latest
    
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_chat_id
  message: >
   {{#success build.status}}
     build {{build.number}} succeeded. Good job.
   {{else}}
     build {{build.number}} failed. Fix me please.
   {{/success}}

trigger:
  branch:
  - master
  event:
  - push

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
