version: "3"

networks:
  ci_pg_db:
    external: false
  ci_ldap_net:
    external: false

services:
  ci_lama:
    image: lama:0.1
    build:
      context: .
      dockerfile: docker/lama/Dockerfile.test
    networks:
      - ci_ldap_net
      - ci_pg_db
    env_file:
      - docker/lama/test.env
    depends_on:
      - ci_dblama
      - ci_ldap
    ports:
      - 0.0.0.0:8888:80
  
  ci_dblama:
    image: postgres:11.2-alpine
    networks:
      - ci_pg_db
    env_file:
      - docker/lama/test.env

  ci_ldap:
    image: docker.clkl.de/ldap/ldap:0.3-lama
    build:
      context: docker/ldap
      dockerfile: Dockerfile.ldap
    env_file: docker/ldap/ldap.env
    networks:
      - ci_ldap_net
