version: '3.7'

services:
  web:
    build:
      context: frontend
      target: 'develop-stage'
    command: /bin/sh -c "npm run serve"
    volumes:
      - ./frontend/lama:/app
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    build:
      context: ./backend/docker/lama
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/lama
    ports:
      - 8000:80
    env_file:
      - ./backend/docker/lama/dev.env
    depends_on:
      - db
      - ldap

  db:
    image: postgres:12.0-alpine
    env_file:
      - ./backend/docker/lama/dev.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ldap:
    image: docker.clkl.de/ldap/ldap:0.3-lama
    build:
      context: backend/docker/ldap
      dockerfile: Dockerfile.ldap
    env_file: ./backend/docker/ldap/ldap.env

  ldap_admin:
    image: docker.clkl.de/ldap/admin:0.1-lama
    build:
      context: backend/docker/ldap
      dockerfile: Dockerfile.admin
    depends_on:
      - ldap
    ports:
      - 0.0.0.0:8888:80
