version: "3"

networks:
  pg_db:
    external: false
  ldap_net:
    external: false

services:
  ci_lama:
    image: lama:0.1
    build:
      context: .
      dockerfile: docker/lama/Dockerfile.test
    networks:
      - ldap_net
      - pg_db
    env_file:
      - docker/lama/test.env
    depends_on:
      - dblama
      - ldap
    ports:
      - 0.0.0.0:8888:80
  
  ci_dblama:
    image: postgres:11.2-alpine
    networks:
      - pg_db
    env_file:
      - docker/lama/test.env

  ci_ldap:
    image: docker.clkl.de/ldap/ldap:0.3-lama
    build:
      context: docker/ldap
      dockerfile: Dockerfile.ldap
    env_file: docker/ldap/ldap.env
    networks:
      - ldap_net

  ci_ldap_admin:
    image: docker.clkl.de/ldap/admin:0.1-lama
    build:
      context: docker/ldap
      dockerfile: Dockerfile.admin
    networks:
      - ldap_net
    depends_on:
      - ldap
    ports:
      - 0.0.0.0:8080:80
